import React, { useState } from 'react';
import {
  Palette,
  Code2,
  Terminal,
  RefreshCw,
  Copy,
  CheckCircle2,
  Sparkles,
  Layers,
  ArrowRight,
} from 'lucide-react';
import { DesignToken } from '../types';

interface DesignTokensPipelineViewProps {
  tokens: DesignToken[];
}

export const DesignTokensPipelineView: React.FC<DesignTokensPipelineViewProps> = ({ tokens }) => {
  const [selectedLayer, setSelectedLayer] = useState<'all' | 'primitive' | 'semantic' | 'component'>('all');
  const [buildTarget, setBuildTarget] = useState<'css' | 'tailwind' | 'ts_constants'>('css');
  const [isBuilding, setIsBuilding] = useState(false);
  const [copied, setCopied] = useState(false);

  const filteredTokens = tokens.filter((t) => selectedLayer === 'all' || t.layer === selectedLayer);

  // Generate output code based on buildTarget
  const generateOutputCode = () => {
    if (buildTarget === 'css') {
      return `/* Generated by Style Dictionary (W3C DTCG Standard) */\n:root {\n${tokens
        .map((t) => `  --${t.name.replace(/\./g, '-')}: ${t.value};`)
        .join('\n')}\n}`;
    } else if (buildTarget === 'tailwind') {
      return `// Tailwind CSS Design Token Extensions\nmodule.exports = {\n  theme: {\n    extend: {\n      colors: {\n        brand: {\n          primary: 'var(--color-semantic-brand-primary)',\n        }\n      }\n    }\n  }\n};`;
    } else {
      return `// TypeScript Constant Definitions\nexport const DESIGN_TOKENS = {\n${tokens
        .map((t) => `  "${t.name}": "${t.value}",`)
        .join('\n')}\n} as const;`;
    }
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generateOutputCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <Palette className="w-6 h-6 text-indigo-600" />
            <span>W3C Design Tokens & CI/CD Pipeline Transformer</span>
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Standardized W3C DTCG tokens transformed via Style Dictionary for web, mobile, and design tools.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              setIsBuilding(true);
              setTimeout(() => setIsBuilding(false), 800);
            }}
            disabled={isBuilding}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold shadow-2xs transition-colors disabled:opacity-50"
          >
            {isBuilding ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            <span>{isBuilding ? 'Running Style Dictionary...' : 'Run CI/CD Token Build'}</span>
          </button>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Token Studio & Alias Chains */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
              Token Registry ({filteredTokens.length})
            </h3>

            <div className="flex items-center bg-slate-100 p-1 rounded-xl border border-slate-200 text-xs font-medium">
              {(['all', 'primitive', 'semantic', 'component'] as const).map((layer) => (
                <button
                  key={layer}
                  onClick={() => setSelectedLayer(layer)}
                  className={`px-2.5 py-1 rounded-lg capitalize transition-colors ${
                    selectedLayer === layer ? 'bg-white text-indigo-700 font-semibold shadow-2xs' : 'text-slate-600 hover:text-slate-900'
                  }`}
                >
                  {layer}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-2 max-h-[500px] overflow-y-auto pr-1">
            {filteredTokens.map((tok) => (
              <div key={tok.id} className="p-3.5 bg-white rounded-xl border border-slate-200/90 shadow-2xs space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold text-slate-900">{tok.name}</span>
                  <span
                    className={`text-[10px] font-bold px-2 py-0.5 rounded capitalize ${
                      tok.layer === 'primitive'
                        ? 'bg-slate-100 text-slate-700'
                        : tok.layer === 'semantic'
                        ? 'bg-indigo-100 text-indigo-800'
                        : 'bg-purple-100 text-purple-800'
                    }`}
                  >
                    {tok.layer}
                  </span>
                </div>

                <div className="flex items-center justify-between text-xs font-mono">
                  <span className="text-slate-500">Value:</span>
                  <div className="flex items-center gap-2">
                    {tok.category === 'color' && (
                      <span className="w-3.5 h-3.5 rounded border border-slate-300 inline-block" style={{ backgroundColor: tok.value.startsWith('#') ? tok.value : '#4f46e5' }} />
                    )}
                    <span className="font-bold text-slate-800">{tok.value}</span>
                  </div>
                </div>

                {tok.aliasOf && (
                  <div className="text-[11px] text-indigo-600 flex items-center gap-1 font-mono">
                    <ArrowRight className="w-3 h-3" />
                    <span>Alias of: {tok.aliasOf}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Style Dictionary Output Transformer */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
              Style Dictionary Output
            </h3>

            <div className="flex items-center bg-slate-100 p-1 rounded-xl border border-slate-200 text-xs font-medium">
              {(['css', 'tailwind', 'ts_constants'] as const).map((target) => (
                <button
                  key={target}
                  onClick={() => setBuildTarget(target)}
                  className={`px-2.5 py-1 rounded-lg uppercase transition-colors ${
                    buildTarget === target ? 'bg-white text-indigo-700 font-semibold shadow-2xs' : 'text-slate-600 hover:text-slate-900'
                  }`}
                >
                  {target.replace('_', ' ')}
                </button>
              ))}
            </div>
          </div>

          <div className="p-4 bg-slate-950 text-slate-200 rounded-2xl border border-indigo-900/50 shadow-xl space-y-3 font-mono text-xs relative">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2">
              <span className="text-indigo-400 font-bold flex items-center gap-2">
                <Terminal className="w-4 h-4 text-indigo-400" />
                <span>dist/tokens.{buildTarget === 'css' ? 'css' : buildTarget === 'tailwind' ? 'config.js' : 'ts'}</span>
              </span>

              <button
                onClick={handleCopyCode}
                className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-white transition-colors"
              >
                {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied!' : 'Copy Code'}</span>
              </button>
            </div>

            <pre className="overflow-x-auto whitespace-pre p-2 text-slate-300 text-[11px]">
              {generateOutputCode()}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};
